/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReservaTuMoto;

import javax.swing.Icon;

/**
 *
 * @author juli
 */
public class PaginaReserva extends javax.swing.JFrame {
    private int idi;
    private Datos dat;
    /**
     * Creates new form PaginaReserva
     */
    public PaginaReserva() {
        initComponents();
    }
    
    public void cargarDatos(Datos datos, int idioma, String modelo, Icon icono){
        this.idi = idioma;
        this.dat = datos;
        this.imagen.setIcon(icono);
        this.modelo.setText(modelo);
        
        this.Titulo.setText(datos.getIdiomas().get(idioma).get(1));
        this.texto.setText(datos.getIdiomas().get(idioma).get(2));
        this.c1texto.setText(datos.getIdiomas().get(idioma).get(3));
        this.c2texto.setText(datos.getIdiomas().get(idioma).get(4));
        this.c3texto.setText(datos.getIdiomas().get(idioma).get(5));
        this.c4texto.setText(datos.getIdiomas().get(idioma).get(6));
        this.c5texto.setText(datos.getIdiomas().get(idioma).get(7));
        this.c5field.setText(datos.getIdiomas().get(idioma).get(8));
        this.c5field2.setText(datos.getIdiomas().get(idioma).get(9));
        
        int index = -1;
        for(int i = 0; i < datos.getReservas().size(); i++){
            if(modelo.contains(datos.getReservas().get(i).get(0))){
                index = i;
            }
        }
        
        for(int i = 1; i < datos.getReservas().get(index).size(); i++){
            this.c4field.addItem(datos.getReservas().get(index).get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        navegacion = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        card = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        campo1 = new javax.swing.JPanel();
        c1texto = new javax.swing.JLabel();
        c1field = new javax.swing.JTextField();
        campo2 = new javax.swing.JPanel();
        c2texto = new javax.swing.JLabel();
        c2field = new javax.swing.JTextField();
        campo3 = new javax.swing.JPanel();
        c3texto = new javax.swing.JLabel();
        c3field = new javax.swing.JTextField();
        campo4 = new javax.swing.JPanel();
        c4texto = new javax.swing.JLabel();
        c4field = new javax.swing.JComboBox<>();
        campo5 = new javax.swing.JPanel();
        c5texto = new javax.swing.JLabel();
        c5field = new javax.swing.JCheckBox();
        c5field2 = new javax.swing.JCheckBox();
        reservar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        root.setBackground(new java.awt.Color(255, 255, 255));

        navegacion.setBackground(new java.awt.Color(255, 255, 255));
        navegacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo.setBackground(new java.awt.Color(254, 254, 254));
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/logo1.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navegacionLayout = new javax.swing.GroupLayout(navegacion);
        navegacion.setLayout(navegacionLayout);
        navegacionLayout.setHorizontalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegacionLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1350, Short.MAX_VALUE))
        );
        navegacionLayout.setVerticalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, Short.MAX_VALUE)
        );

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1602, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2254, Short.MAX_VALUE)
        );

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/imagenes/ktm-duke1.jpg"))); // NOI18N

        cancelar.setBackground(new java.awt.Color(254, 254, 254));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/cancelar1.png"))); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("RESERVA");

        texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        texto.setText("Complete los campos para reservar: ");

        modelo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        modelo.setText("KTM DUKE-390");

        campo1.setBackground(new java.awt.Color(255, 255, 255));

        c1texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c1texto.setText("Nombre Completo:");

        c1field.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        c1field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campo1Layout = new javax.swing.GroupLayout(campo1);
        campo1.setLayout(campo1Layout);
        campo1Layout.setHorizontalGroup(
            campo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(c1texto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1field)
                .addGap(288, 288, 288))
        );
        campo1Layout.setVerticalGroup(
            campo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(campo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1field, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1texto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        campo2.setBackground(new java.awt.Color(255, 255, 255));

        c2texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c2texto.setText("Email:");

        c2field.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        c2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campo2Layout = new javax.swing.GroupLayout(campo2);
        campo2.setLayout(campo2Layout);
        campo2Layout.setHorizontalGroup(
            campo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(c2texto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2field)
                .addGap(288, 288, 288))
        );
        campo2Layout.setVerticalGroup(
            campo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(campo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2field, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2texto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        campo3.setBackground(new java.awt.Color(255, 255, 255));

        c3texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c3texto.setText("Nº Teléfono:");

        c3field.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        c3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campo3Layout = new javax.swing.GroupLayout(campo3);
        campo3.setLayout(campo3Layout);
        campo3Layout.setHorizontalGroup(
            campo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo3Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(c3texto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3field)
                .addGap(288, 288, 288))
        );
        campo3Layout.setVerticalGroup(
            campo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(campo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c3field, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3texto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        campo4.setBackground(new java.awt.Color(255, 255, 255));

        c4texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c4texto.setText("Fecha:");

        c4field.setBackground(new java.awt.Color(254, 254, 254));
        c4field.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        c4field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        c4field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campo4Layout = new javax.swing.GroupLayout(campo4);
        campo4.setLayout(campo4Layout);
        campo4Layout.setHorizontalGroup(
            campo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo4Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(c4texto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4field, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        campo4Layout.setVerticalGroup(
            campo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(campo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c4texto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4field, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        campo5.setBackground(new java.awt.Color(255, 255, 255));

        c5texto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c5texto.setText("Contratos:");

        c5field.setBackground(new java.awt.Color(255, 255, 255));
        c5field.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c5field.setText("<html>Acepto recibir información adicional via email<hmtl>");
        c5field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5fieldActionPerformed(evt);
            }
        });

        c5field2.setBackground(new java.awt.Color(255, 255, 255));
        c5field2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        c5field2.setText("<html>Acepto recibir confirmación de mi reserva via sms<html>");
        c5field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5field2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campo5Layout = new javax.swing.GroupLayout(campo5);
        campo5.setLayout(campo5Layout);
        campo5Layout.setHorizontalGroup(
            campo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo5Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(c5texto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(campo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c5field, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5field2, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        campo5Layout.setVerticalGroup(
            campo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campo5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(campo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c5texto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5field, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c5field2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        reservar.setBackground(new java.awt.Color(254, 254, 254));
        reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/aceptar1.png"))); // NOI18N
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(campo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardLayout.createSequentialGroup()
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cardLayout.createSequentialGroup()
                        .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardLayout.createSequentialGroup()
                                .addGap(476, 476, 476)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cardLayout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addComponent(texto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(673, 673, 673)
                .addComponent(reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(rootLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 1528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void c1fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1fieldActionPerformed

    private void c2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2fieldActionPerformed

    private void c3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3fieldActionPerformed

    private void c5fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5fieldActionPerformed

    private void c5field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5field2ActionPerformed

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
        PaginaMensaje paginaMensaje = new PaginaMensaje();
        paginaMensaje.setVisible(true);
        if(this.c1field.getText().equals("")){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else if(this.c2field.getText().equals("")){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else if(this.c3field.getText().equals("")){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else if(this.c4field.getSelectedItem().toString().equals("-")){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else if(this.c5field.isSelected() == false){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else if(this.c5field2.isSelected() == false){
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(23));
        }else{
            paginaMensaje.setTexto(this.dat.getIdiomas().get(idi).get(22));
            
            int index = -1;
            for(int i = 0; i < dat.getReservas().size(); i++){
                if(this.modelo.getText().contains(dat.getReservas().get(i).get(0))){
                    index = i;
                }
            }
            
            for(int i = 0; i < dat.getReservas().get(index).size(); i++){
                if(dat.getReservas().get(index).get(i).contains(this.c4field.getSelectedItem().toString())){
                    dat.getReservas().get(index).remove(i);
                    break;
                }
            }
            
            this.dispose();
        }
        
        
        
        
        
    }//GEN-LAST:event_reservarActionPerformed

    private void c4fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel body;
    private javax.swing.JTextField c1field;
    private javax.swing.JLabel c1texto;
    private javax.swing.JTextField c2field;
    private javax.swing.JLabel c2texto;
    private javax.swing.JTextField c3field;
    private javax.swing.JLabel c3texto;
    private javax.swing.JComboBox<String> c4field;
    private javax.swing.JLabel c4texto;
    private javax.swing.JCheckBox c5field;
    private javax.swing.JCheckBox c5field2;
    private javax.swing.JLabel c5texto;
    private javax.swing.JPanel campo1;
    private javax.swing.JPanel campo2;
    private javax.swing.JPanel campo3;
    private javax.swing.JPanel campo4;
    private javax.swing.JPanel campo5;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel card;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton logo;
    private javax.swing.JLabel modelo;
    private javax.swing.JPanel navegacion;
    private javax.swing.JButton reservar;
    private javax.swing.JPanel root;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
