/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReservaTuMoto;

/**
 *
 * @author juli
 */
public class PaginaPrincipal extends javax.swing.JFrame {
    private int idiomaActual = 0;
    private Datos datos;
    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
        cargarDatos();
    }
    
    private void cargarDatos(){
        this.datos = new Datos();
        
        this.marca.addItem(datos.getIdiomas().get(this.idiomaActual).get(24));
        for(String marca1 : datos.getMarcas()) {
            this.marca.addItem(marca1);
        }
        
        this.modelo.addItem(datos.getIdiomas().get(this.idiomaActual).get(25));
        for(String modelo1 : datos.getModelos()) {
            this.modelo.addItem(modelo1);
        }
        
        this.fecha.addItem(datos.getIdiomas().get(this.idiomaActual).get(26));
        for(String fecha1 : datos.getFechas()) {
            this.fecha.addItem(fecha1);
        }
        //coger primer dato de cada fila
        for(int i = 0; i < datos.getIdiomas().size(); i++) {
            comboIdioma.addItem(datos.getIdiomas().get(i).get(0));
        }

        this.titulo1.setText(datos.getIdiomas().get(idiomaActual).get(10));
        this.descripcion1.setText(datos.getIdiomas().get(idiomaActual).get(11));
        
        this.titulo2.setText(datos.getIdiomas().get(idiomaActual).get(13));
        this.descripcion2.setText(datos.getIdiomas().get(idiomaActual).get(14));
        
        this.titulo3.setText(datos.getIdiomas().get(idiomaActual).get(16));
        this.descripcion3.setText(datos.getIdiomas().get(idiomaActual).get(17));
        
        this.titulo4.setText(datos.getIdiomas().get(idiomaActual).get(19));
        this.descripcion4.setText(datos.getIdiomas().get(idiomaActual).get(20));
        
        //menu
        this.menuVentana.setText(datos.getIdiomas().get(idiomaActual).get(27));
        this.menuAcciones.setText(datos.getIdiomas().get(idiomaActual).get(28));
        this.ventana.setText(datos.getIdiomas().get(idiomaActual).get(29));
        this.tamaño1.setText(datos.getIdiomas().get(idiomaActual).get(30));
        this.tamaño2.setText(datos.getIdiomas().get(idiomaActual).get(31));
        this.colorFondo.setText(datos.getIdiomas().get(idiomaActual).get(32));
        this.color1.setText(datos.getIdiomas().get(idiomaActual).get(33));
        this.color2.setText(datos.getIdiomas().get(idiomaActual).get(34));
        this.descargar.setText(datos.getIdiomas().get(idiomaActual).get(35));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        navegacion = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        marca = new javax.swing.JComboBox<>();
        modelo = new javax.swing.JComboBox<>();
        fecha = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JButton();
        comboIdioma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        card = new javax.swing.JPanel();
        imagen1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JLabel();
        botonInfo1 = new javax.swing.JButton();
        botonReservar1 = new javax.swing.JButton();
        card1 = new javax.swing.JPanel();
        imagen2 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JLabel();
        botonInfo2 = new javax.swing.JButton();
        botonReservar2 = new javax.swing.JButton();
        card2 = new javax.swing.JPanel();
        imagen3 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        descripcion3 = new javax.swing.JLabel();
        botonInfo3 = new javax.swing.JButton();
        botonReservar3 = new javax.swing.JButton();
        card3 = new javax.swing.JPanel();
        imagen4 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        descripcion4 = new javax.swing.JLabel();
        botonInfo4 = new javax.swing.JButton();
        botonReservar4 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuVentana = new javax.swing.JMenu();
        ventana = new javax.swing.JMenu();
        tamaño1 = new javax.swing.JMenuItem();
        tamaño2 = new javax.swing.JMenuItem();
        colorFondo = new javax.swing.JMenu();
        color1 = new javax.swing.JMenuItem();
        color2 = new javax.swing.JMenuItem();
        menuAcciones = new javax.swing.JMenu();
        descargar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva tu Moto");

        root.setBackground(new java.awt.Color(255, 255, 255));

        navegacion.setBackground(new java.awt.Color(255, 255, 255));
        navegacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo.setBackground(new java.awt.Color(254, 254, 254));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/logo1.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        marca.setBackground(new java.awt.Color(254, 254, 254));
        marca.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        marca.setName(""); // NOI18N

        modelo.setBackground(new java.awt.Color(254, 254, 254));
        modelo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        fecha.setBackground(new java.awt.Color(254, 254, 254));
        fecha.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        buscar.setBackground(new java.awt.Color(254, 254, 254));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/buscar1.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        comboIdioma.setBackground(new java.awt.Color(254, 254, 254));
        comboIdioma.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        comboIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdiomaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/idioma1.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout navegacionLayout = new javax.swing.GroupLayout(navegacion);
        navegacion.setLayout(navegacionLayout);
        navegacionLayout.setHorizontalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegacionLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(comboIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navegacionLayout.setVerticalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navegacionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navegacionLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(comboIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(255, 255, 255));

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        imagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/imagenes/ktm-duke1.jpg"))); // NOI18N

        titulo1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo1.setText("TITULO1");

        descripcion1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        descripcion1.setText("<html>nuevo aspecto agresivo respalda su característico comportamiento afilado,  su potente motor de 399 cc y su avanzada tecnología.<html>");
        descripcion1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botonInfo1.setBackground(new java.awt.Color(254, 254, 254));
        botonInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/info1.png"))); // NOI18N
        botonInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfo1ActionPerformed(evt);
            }
        });

        botonReservar1.setBackground(new java.awt.Color(254, 254, 254));
        botonReservar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/confirmar1.png"))); // NOI18N
        botonReservar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReservar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReservar1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botonInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        descripcion1.getAccessibleContext().setAccessibleName("");

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/imagenes/kawa1.png"))); // NOI18N

        titulo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo2.setText("TITULO1");

        descripcion2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        descripcion2.setText("<html>nuevo aspecto agresivo respalda su característico comportamiento afilado,  su potente motor de 399 cc y su avanzada tecnología.<html>");
        descripcion2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botonInfo2.setBackground(new java.awt.Color(254, 254, 254));
        botonInfo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/info1.png"))); // NOI18N
        botonInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfo2ActionPerformed(evt);
            }
        });

        botonReservar2.setBackground(new java.awt.Color(254, 254, 254));
        botonReservar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/confirmar1.png"))); // NOI18N
        botonReservar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReservar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReservar2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botonInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        imagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/imagenes/ducati1.png"))); // NOI18N

        titulo3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo3.setText("TITULO1");

        descripcion3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        descripcion3.setText("<html>nuevo aspecto agresivo respalda su característico comportamiento afilado,  su potente motor de 399 cc y su avanzada tecnología.<html>");
        descripcion3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botonInfo3.setBackground(new java.awt.Color(254, 254, 254));
        botonInfo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/info1.png"))); // NOI18N
        botonInfo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfo3ActionPerformed(evt);
            }
        });

        botonReservar3.setBackground(new java.awt.Color(254, 254, 254));
        botonReservar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/confirmar1.png"))); // NOI18N
        botonReservar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(card2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReservar3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addComponent(imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReservar3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botonInfo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        card3.setBackground(new java.awt.Color(255, 255, 255));
        card3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        imagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/imagenes/yamaha1.jpg"))); // NOI18N

        titulo4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo4.setText("TITULO1");

        descripcion4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        descripcion4.setText("<html>nuevo aspecto agresivo respalda su característico comportamiento afilado,  su potente motor de 399 cc y su avanzada tecnología.<html>");
        descripcion4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botonInfo4.setBackground(new java.awt.Color(254, 254, 254));
        botonInfo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/info1.png"))); // NOI18N
        botonInfo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfo4ActionPerformed(evt);
            }
        });

        botonReservar4.setBackground(new java.awt.Color(254, 254, 254));
        botonReservar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReservaTuMoto/iconos/confirmar1.png"))); // NOI18N
        botonReservar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(card3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(botonInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonReservar4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addComponent(imagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReservar4, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botonInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2011, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuVentana.setText("File");
        menuVentana.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        ventana.setText("jMenu3");
        ventana.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        tamaño1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tamaño1.setText("jMenuItem2");
        ventana.add(tamaño1);

        tamaño2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tamaño2.setText("jMenuItem3");
        ventana.add(tamaño2);

        menuVentana.add(ventana);

        colorFondo.setText("jMenu4");
        colorFondo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        color1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        color1.setText("jMenuItem4");
        colorFondo.add(color1);

        color2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        color2.setText("jMenuItem5");
        colorFondo.add(color2);

        menuVentana.add(colorFondo);

        menuBar.add(menuVentana);

        menuAcciones.setText("Edit");
        menuAcciones.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        descargar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        descargar.setText("jMenuItem1");
        menuAcciones.add(descargar);

        menuBar.add(menuAcciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 2863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void botonInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfo1ActionPerformed
        // TODO add your handling code here:
        PaginaInfo paginaInfo = new PaginaInfo(); 
        paginaInfo.cargarDatos(datos, this.imagen1.getIcon(), 10, 12, this.idiomaActual);
        paginaInfo.setVisible(true);
    }//GEN-LAST:event_botonInfo1ActionPerformed

    private void botonReservar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservar1ActionPerformed
        // TODO add your handling code here:
        PaginaReserva paginaReserva = new PaginaReserva();
        paginaReserva.cargarDatos(datos, this.idiomaActual, this.titulo1.getText(), this.imagen1.getIcon());
        paginaReserva.setVisible(true);
    }//GEN-LAST:event_botonReservar1ActionPerformed

    private void botonInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfo2ActionPerformed
        // TODO add your handling code here:
        PaginaInfo paginaInfo = new PaginaInfo(); 
        paginaInfo.cargarDatos(datos, this.imagen2.getIcon(), 13, 15, this.idiomaActual);
        paginaInfo.setVisible(true);
        
    }//GEN-LAST:event_botonInfo2ActionPerformed

    private void botonReservar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservar2ActionPerformed
        // TODO add your handling code here:
        PaginaReserva paginaReserva = new PaginaReserva();
        paginaReserva.cargarDatos(datos, this.idiomaActual, this.titulo2.getText(), this.imagen2.getIcon());
        paginaReserva.setVisible(true);
    }//GEN-LAST:event_botonReservar2ActionPerformed

    private void botonInfo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfo3ActionPerformed
        // TODO add your handling code here:
        PaginaInfo paginaInfo = new PaginaInfo(); 
        paginaInfo.cargarDatos(datos, this.imagen3.getIcon(), 16, 18, this.idiomaActual);
        paginaInfo.setVisible(true);
    }//GEN-LAST:event_botonInfo3ActionPerformed

    private void botonReservar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservar3ActionPerformed
        // TODO add your handling code here:
        PaginaReserva paginaReserva = new PaginaReserva();
        paginaReserva.cargarDatos(datos, this.idiomaActual, this.titulo3.getText(), this.imagen3.getIcon());
        paginaReserva.setVisible(true);
    }//GEN-LAST:event_botonReservar3ActionPerformed

    private void botonInfo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfo4ActionPerformed
        // TODO add your handling code here:
        PaginaInfo paginaInfo = new PaginaInfo(); 
        paginaInfo.cargarDatos(datos, this.imagen4.getIcon(), 19, 21, this.idiomaActual);
        paginaInfo.setVisible(true);
    }//GEN-LAST:event_botonInfo4ActionPerformed

    private void botonReservar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservar4ActionPerformed
        // TODO add your handling code here:
        PaginaReserva paginaReserva = new PaginaReserva();
        paginaReserva.cargarDatos(datos, this.idiomaActual, this.titulo4.getText(), this.imagen4.getIcon());
        paginaReserva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonReservar4ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        boolean flag = true, flag1 = true, flag2 = true, flag3 = true;
        
        if(this.marca.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(24))  &&
           this.modelo.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(25))  &&
           this.fecha.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(26))){
            
            this.card.setVisible(flag);
            this.card1.setVisible(flag1);
            this.card2.setVisible(flag2);
            this.card3.setVisible(flag3);
            return;
        }
        
        
        //comprobar marca
        if(!this.marca.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(24))){
            if(!this.titulo1.getText().contains(this.marca.getSelectedItem().toString())){
                flag = false;
            }
            if(!this.titulo2.getText().contains(this.marca.getSelectedItem().toString())){
                flag1 = false;
            }
            if(!this.titulo3.getText().contains(this.marca.getSelectedItem().toString())){
                flag2 = false;
            }
            if(!this.titulo4.getText().contains(this.marca.getSelectedItem().toString())){
                flag3 = false;
            }
        }
        
        
        //comprobar modelo
        if(!this.modelo.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(25))){
            if(!this.titulo1.getText().contains(this.modelo.getSelectedItem().toString())){
                flag = false;
            }
            if(!this.titulo2.getText().contains(this.modelo.getSelectedItem().toString())){
                flag1 = false;
            }
            if(!this.titulo3.getText().contains(this.modelo.getSelectedItem().toString())){
                flag2 = false;
            }
            if(!this.titulo4.getText().contains(this.modelo.getSelectedItem().toString())){
                flag3 = false;
            }
        }
        
        
        //comprobar fechas
        if(!this.fecha.getSelectedItem().toString().equals(this.datos.getIdiomas().get(idiomaActual).get(26))){
            //primera comprobacion
            boolean comprobacion = true;
            for(int i = 1; i < this.datos.getReservas().get(0).size(); i++){
                if(this.datos.getReservas().get(0).get(i).equals(this.fecha.getSelectedItem().toString())){
                    comprobacion = false;
                }
            }
            if(comprobacion){
                flag = false;
            }
            
            //segunda
            comprobacion = true;
            for(int i = 1; i < this.datos.getReservas().get(1).size(); i++){
                if(this.datos.getReservas().get(1).get(i).equals(this.fecha.getSelectedItem().toString())){
                    comprobacion = false;
                }
            }
            if(comprobacion){
                flag1 = false;
            }

            //tercera
            comprobacion = true;
            for(int i = 1; i < this.datos.getReservas().get(2).size(); i++){
                if(this.datos.getReservas().get(2).get(i).equals(this.fecha.getSelectedItem().toString())){
                    comprobacion = false;
                }
            }
            if(comprobacion){
                flag2 = false;
            }
            
            //cuarta
            comprobacion = true;
            for(int i = 1; i < this.datos.getReservas().get(3).size(); i++){
                if(this.datos.getReservas().get(3).get(i).equals(this.fecha.getSelectedItem().toString())){
                    comprobacion = false;
                }
            }
            if(comprobacion){
                flag3 = false;
            }
            
        }
        
        
        this.card.setVisible(flag);
        this.card1.setVisible(flag1);
        this.card2.setVisible(flag2);
        this.card3.setVisible(flag3);
        
    }//GEN-LAST:event_buscarActionPerformed

    private void comboIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdiomaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String aux = (String) this.comboIdioma.getSelectedItem();
        if (aux.equals("Español")) {
            this.idiomaActual = 0;
        } else if (aux.equals("Ingles")) {
            this.idiomaActual = 1;
        }

        this.descripcion1.setText(datos.getIdiomas().get(idiomaActual).get(11));
        this.descripcion2.setText(datos.getIdiomas().get(idiomaActual).get(14));
        this.descripcion3.setText(datos.getIdiomas().get(idiomaActual).get(17));
        this.descripcion4.setText(datos.getIdiomas().get(idiomaActual).get(20));
        this.marca.removeAllItems();
        this.marca.addItem(datos.getIdiomas().get(this.idiomaActual).get(24));
        for (String marca1 : datos.getMarcas()) {
            this.marca.addItem(marca1);
        }

        this.modelo.removeAllItems();
        this.modelo.addItem(datos.getIdiomas().get(this.idiomaActual).get(25));
        for (String modelo1 : datos.getModelos()) {
            this.modelo.addItem(modelo1);
        }

        this.fecha.removeAllItems();
        this.fecha.addItem(datos.getIdiomas().get(this.idiomaActual).get(26));
        for (String fecha1 : datos.getFechas()) {
            this.fecha.addItem(fecha1);
        }
        
        //menu
        this.menuVentana.setText(datos.getIdiomas().get(idiomaActual).get(27));
        this.menuAcciones.setText(datos.getIdiomas().get(idiomaActual).get(28));
        this.ventana.setText(datos.getIdiomas().get(idiomaActual).get(29));
        this.tamaño1.setText(datos.getIdiomas().get(idiomaActual).get(30));
        this.tamaño2.setText(datos.getIdiomas().get(idiomaActual).get(31));
        this.colorFondo.setText(datos.getIdiomas().get(idiomaActual).get(32));
        this.color1.setText(datos.getIdiomas().get(idiomaActual).get(33));
        this.color2.setText(datos.getIdiomas().get(idiomaActual).get(34));
        this.descargar.setText(datos.getIdiomas().get(idiomaActual).get(35));
    }//GEN-LAST:event_comboIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton botonInfo1;
    private javax.swing.JButton botonInfo2;
    private javax.swing.JButton botonInfo3;
    private javax.swing.JButton botonInfo4;
    private javax.swing.JButton botonReservar1;
    private javax.swing.JButton botonReservar2;
    private javax.swing.JButton botonReservar3;
    private javax.swing.JButton botonReservar4;
    private javax.swing.JButton buscar;
    private javax.swing.JPanel card;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JMenuItem color1;
    private javax.swing.JMenuItem color2;
    private javax.swing.JMenu colorFondo;
    private javax.swing.JComboBox<String> comboIdioma;
    private javax.swing.JMenuItem descargar;
    private javax.swing.JLabel descripcion1;
    private javax.swing.JLabel descripcion2;
    private javax.swing.JLabel descripcion3;
    private javax.swing.JLabel descripcion4;
    private javax.swing.JComboBox<String> fecha;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logo;
    private javax.swing.JComboBox<String> marca;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuVentana;
    private javax.swing.JComboBox<String> modelo;
    private javax.swing.JPanel navegacion;
    private javax.swing.JPanel root;
    private javax.swing.JMenuItem tamaño1;
    private javax.swing.JMenuItem tamaño2;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JMenu ventana;
    // End of variables declaration//GEN-END:variables
}
